icatproject/python-icat

icat/entity.py
It may occasionally be convenient to get a mapping with an entity object's attributes.  For instance, one may do nice things like string formatting:
```python
>>> inv
(investigation){
createId = "simple/root"
createTime = 2018-02-05 11:30:14+00:00
id = 3
modId = "simple/root"
modTime = 2018-02-05 11:30:14+00:00
endDate = 2012-08-06 01:10:08+00:00
name = "12100409-ST"
startDate = 2012-07-26 15:44:24+00:00
title = "NiO SC OF1 JUH HHL"
visitId = "1.1-P"
}
>>> "%(name)s-%(visitId)s" % inv.as_dict()
'12100409-ST-1.1-P'
```
=> Add a method Entity.as_dict().

CHANGES, doc/src/client.rst, icat/client.py, icat/dumpfile.py, wipeicat.py
Add a method `Client.autoRefresh()` that may be called from client code to prevent the session from expiring.  The method is designed to be as cheap as possible (it only calls `Client.refresh()` if needed and does not make any client calls as long as there is still enough time left in the session) so that it may be called often in a loop without causing needless overhead.
This resolves #46.
=> Add a Client.autoRefresh() method

icat/ids.py, tests/test_06_ids.py
The IDS Write API call is proposed in icatproject/ids.server#67.  This PR adds support for the call on the client side.  It should be merged as soon as the PR for the Write call is merged & released in ids.server.
=> Add support for the IDS Write API call

CHANGES, doc/icatdata-4.10.xsd, icat/client.py, icat/entities.py
The upcoming version 4.10.0 of `icat.server` will feature some schema additions. Obviously, we want to support this on the client side.
As of writing this PR supports the last snapshot release `icat.server-4.10.0-20190212.104517-1`. Obviously, we will wait for the official release before merge.
=> Add support for icat.server 4.10

icat/client.py, icat/config.py, icat/icatcheck.py, icat/ids.py, tests/test_07_entity_sort.py
Fixes:
- Do not use mutable objects as default parameter value.
- Avoid modifying mutable parameters unless this is the intended behavior.
Both is very bad coding style and may have unexpected side effects.
=> Fix bad coding style dealing with function parameters

CHANGES.rst, MANIFEST.in, Makefile, doc/src/conf.py, doc/src/config.rst, doc/src/dumpfile.rst, doc/src/icatdump.rst, doc/src/icatingest.rst, doc/src/index.rst, doc/src/scripts.rst, doc/src/wipeicat.rst, icatdump.py, icatingest.py, python-icat.spec, wipeicat.py
Add documentation for the command line scripts `icatdump`, `icatingest`, and `wipeicat`.  This also includes man pages.
=> Add documentation for the command line scripts

CHANGES.rst, README.rst, setup.py
suds-community has been evaluated and found to work.
- Update the README to suggest either suds-jurko or suds-community.
- List suds-community as a requirement in setup.py.
(Unfortunately, it seems that one must point to one particular package.  There don't seem to be a way to spell "any package providing the suds capability" here.)
- Remove the note on the bug in the original Suds dealing with datetime values from the README.  The original Suds version is not recommended anyway, no need to provide workarounds for bugs in that version.
Close #67.
=> Suds community

CHANGES.rst, doc/examples/addfile.py, doc/src/config.rst, icat/client.py, icat/config.py, icat/dumpfile.py, icat/dumpfile_xml.py, icatdump.py, icatingest.py, tests/conftest.py, tests/test_01_config.py, tests/test_05_dump.py, tests/test_05_dumpfile.py, tests/test_05_setup.py, tests/test_06_ids.py, tests/test_06_ingest.py
Add support for the [pathlib](https://docs.python.org/3/library/pathlib.html) Python standard  library module (added in Python 3.4). Methods that take a file name argument, such as [icat.client.putData()](https://python-icat.readthedocs.io/en/latest/client.html#icat.client.Client.putData) also accept a `Path` object. All internal processing of filesystem paths is changed to use `pathlib` where appropriate.
This implements and closes #66.
=> Add pathlib support

CHANGES.rst, icat/client.py
There is a somewhat obscure issue related with the `apiversion` attribute of class `Client`.  It manifests itself in very special conditions:
- only relevant for Python 2,
- only seem to become apparent when talking to an `icat.server` that is a snapshot version,
- only manifests itself in very particular situations: it leads to failed tests that try to dump YAML into a memory buffer.
The symptom:
```python
>>> import io
>>> import icat.dumpfile_yaml
>>> from icat.dumpfile import open_dumpfile
>>> 
>>> client.apiversion
StrictVersion ('4.11a1')
>>> type(client.apiversion)
<type 'instance'>
>>> query = "SELECT f FROM Facility f" 
>>> stream = io.BytesIO()
>>> with open_dumpfile(client, stream, 'YAML', 'w') as dumpfile:
...     dumpfile.writedata([query])
... 
Traceback (most recent call …
```
=> Fix encoding issue with client.apiversion and Python 2

CHANGES.rst, doc/src/exception.rst, icat/exception.py
`EntityTypeError` is raised in situations where a `TypeError` would also be appropriate. This adds `TypeError` as additional ancestor.
=> Add TypeError as additional ancestor of EntityTypeError

CHANGES.rst, doc/src/tutorial-search.rst, icat/client.py, icat/helper.py, icat/query.py, icatdump.py, tests/test_05_dumpfile.py, tests/test_06_client.py, tests/test_06_query.py, tests/test_09_deprecations.py
icatproject/icat.server#246 adds support for queries searching for multiple fields.  This PR adds client side support for this in python-icat. It adds special handling of the case that the ICAT `search()` API method returns a `fieldSet`.
This is just the minimal implementation and not yet final.  Still todo:
=> Add support for searching for multiple fields

CHANGES.rst, icat/query.py, tests/test_06_query.py
Omit the brackets for an aggregate function if searching for multiple attributes and the aggregate function is DISTINCT in the `Query` class. This works around an oddity in the parser for JPQL search expressions in `icat.server`.
Close #76.
=> Work around an issue in icat.server using DISTINCT in search queries for multiple fields

CHANGES.rst, doc/src/tutorial-search.rst, icat/client.py, tests/test_06_client.py, tests/test_06_query.py
While working on #81, I noticed another issue in the results of a searching for multiple fields: the `Client.search()` method returns a list of the results. There are situation where it may be convenient to turn that list into a set and in general this works. Note that `Entity` objects are hashable even though they are mutable and that has been made particularly with the intention to allow them to be added as an item to a set.
Now:
```python
>>> query = Query(client, "Investigation")
>>> res = client.search(query)
>>> set(res)
{(investigation){
createId = "simple/root"
createTime = 2021-04-13 08:47:18+02:00
id = 31
modId = "simple/root"
modTime = 2021-04-13 08:47:18+02:00
doi = "00.0815/inv-00122"
name = "08100122-EF"
startDate = 2008-03-13 11:39:42+01:00
title = "Durol single crystal" …
```
=> Change the search result in the case of multiple fields from list to tuple

CHANGES.rst, doc/src/exception.rst, icat/exception.py, icat/query.py, tests/test_06_query.py
- Remove the error condition that prevented to add related objects in a one to many relationships to the `ORDER BY` clause in class `Query`.  Still, emit a warning rather then an error because this may have surprising effects for the search results.
- Add a new warning class `QueryOneToManyOrderWarning` for that purpose and a new class `QueryWarning` as common base for `QueryNullableOrderWarning` and `QueryOneToManyOrderWarning`.
Closes #83.
=> Enable ordering on one to many relationships in class Query

CHANGES.rst, icat/dump_queries.py, icat/exception.py, icat/query.py, tests/test_06_query.py
Add an argument `join_specs` to the constructor of class `Query` that allows to override the join specification to be used in the created query for selected related objects.   Do not emit `QueryNullableOrderWarning` or `QueryOneToManyOrderWarning` if the concerned relation is in `join_specs`. This has been discussed in #84.
Draft, still missing:
=> Implement a way to control the join specification used in class Query

CHANGES.rst, doc/src/tutorial-search.rst, icat/query.py, tests/test_06_query.py
Since my last PR, I went back and made some changes to my implementation of #86. I've created a new branch for this as we would like to target this for a 0.20.0 but also it was easier for me to start from a fresh branch.
The changes mean that when conditions are put into `self.conditions`, the key of the condition becomes a tuple:
`{("title", "UPPER"): "like '%PolICE%'"}`
This means that a user can create a condition in the same way that they do in 0.19.0. A user will not notice any difference with these changes, but they will be able to make use of the new feature if desired.
Where `self.conditions` is accessed, I have made changes to work with the new key format, particularly in `__str__`.
I've tried to address all of your comments of my previous implementation:
- I've added a test in …
=> Support for JPQL Functions on Query Conditions

CHANGES.rst, icat/query.py, tests/test_06_query.py
=> Fix join_specs not taken into account in Query.copy() and Query.__repr__()

.rtd-require, CHANGES.rst
Pin `docutils<0.18` when building the documentation at Read the Docs to fix build errors.  Ref. sphinx-doc/sphinx#9727.
=> Fix documentation build

CHANGES.rst, icat/query.py, tests/test_06_query.py
Add `Query.select_clause`, `Query.join_clause`, `Query.where_clause`, `Query.order_clause`, `Query.include_clause`, and `Query.limit_clause`.  These are all read only attributes to access the respective clauses of the query string.  The attributes are also used internally to compile the final query string.  So overriding them in derived classes would work to change the behavior of the `Query` class.
This has been [proposed in a comment](https://github.com/icatproject/python-icat/pull/97#issuecomment-1014438191) in #97.
=> Add read only attributes for the various clauses of a query

CHANGES.rst, doc/examples/add-investigation-data.py, doc/examples/add-job.py, doc/examples/create-investigation.py, doc/examples/create-sampletype.py, doc/examples/init-icat.py, doc/examples/querytest.py
Calling `yaml.load()` without providing the `Loader` argument has been deprecated in PyYAML 5.1 and been dropped in PyYAML 6.0. This updates several example scripts to call `yaml.safe_load()` instead than `yaml.load()` (which is essentially the same as adding a `SafeLoader` argument in the `yaml.load()` call).
Note that while the change is only in examples, some of them are also used in the test suite. So this change also fixes the tests to fail with PyYAML 6.0.
=> Fix tests failing with PyYAML 6.0

CHANGES.rst, doc/src/config.rst, doc/src/tutorial-config-advanced.rst, doc/tutorial/config-preset.py, icat/config.py, tests/test_01_config.py, tests/test_09_deprecations.py
Add a `preset` keyword argument to the constructor of class `icat.config.Config`.  If set, it must be a mapping of configuration variable names to values. This will override the default values of the respective configuration variables.
In difference to what was suggested in #77, I decided to name that keyword argument `preset` and to make the values set in the argument only defaults, e.g. settings in command line arguments, environment variables, and configuration files still take precedence.
Deprecate the module variable `icat.config.defaultsection` in favour of this new feature.
Close #77.
=> Allow to directly pass configuration values in the icat.config.Config() call

CHANGES.rst, doc/src/tutorial-create.rst, doc/src/tutorial-ids.rst, doc/src/tutorial-search.rst, doc/tutorial/config-sub-commands.py, icat/client.py, icat/entities.py, icat/entity.py, tests/test_06_client.py
This makes the `obj` argument to `icat.client.Client.new()` case insensitive, if it is a string, e.g. a type name. It closes #102.
In detail:
- add a class method `icat.entity.Entity.getInstanceName()` that returns the instance name, e.g. the name of the type as declared in the WSDL.
- add each class with the instance name (as before) and with the lower case instance name (new) as key to the client typemap.
- lookup the lowercase `obj` argument in the typemap in `icat.client.Client.new()`.
Draft, still missing: documentation and tests.
=> Make the obj argument to client.new() case insensitive

.gitignore, CHANGES.rst, MANIFEST.in, Makefile, README.rst, doc/src/conf.py, doc/src/helper.rst, icat/client.py, icat/helper.py, icat/ids.py, python-icat.spec, setup.py, tests/conftest.py, tests/test_01_helper.py
Review tool chain to build the package:
- switch from `distutils` to `setuptools` in `setup.py` where appropriate,
- generate a `_meta` module to store the version number,
- misc review.
Furthermore add a helper class `icat.helper.Version` based on `packaging.version.Version` to replace `distutils.version.StrictVersion`.
Close #98.
=> Review build tool chain

CHANGES.rst, doc/src/install.rst, tests/conftest.py, tests/test_05_dump.py, tests/test_05_dumpfile.py, tests/test_05_legacy_ingest.py, tests/test_05_setup.py, tests/test_06_ingest.py
Fix the test suite so that it does not completely fail if either `PyYAML` or `lxml` is not available. Only the tests that depend on the respective library module will be skipped if it is not available.
Close #115.
=> Fix the test suite to work if either PyYAML or lxml is not available

CHANGES.rst, doc/icatdata-4.10.xsd, doc/icatdata-4.3.xsd, doc/icatdata-4.4.xsd, doc/icatdata-4.7.xsd, doc/icatdata-5.0.xsd
Extend `icatdata`  XML Schema Definition files:
Add new `entityReference` types:
- `dataCollectionRef` defining an extra attribute `doi`,
- `studyRef` defining an extra attribute `pid`.
Add extra attributes to existing `entityReference` types:
- `doi` to `datafileRef`,
- `doi` to `datasetRef`,
- `funderIdentifier` to `fundingReferenceRef`,
- `pid` to `instrumentRef`,
- `doi` to `investigationRef`,
- `pid` to `parameterTypeRef`,
- `pid` to `sampleRef`,
- `email` and `orcidId` to `userRef`.
In all cases, these extra attributes allow the respective entity objects to be referenced by those attributes. E.g. you could have something like
```xml
<icatdata>
<data>
<dataset id="Dataset_1">
<datasetInstruments>
<instrument pid="doi:10.5442/NI000004"/>
</datasetInstruments>
<datasetTechniques> …
```
=> Extend icatdata XSD adding extra attributes to reference objects

CHANGES.rst, icat/config.py
- Freeze the variable names in the `icat.config.Configuration` object before returning it from `icat.config.Config.getconfig()`,
- At the same, delete the `_config` attribute in this object.
Close #119
=> Remove attribute icat.config.Configuration._config

CHANGES.rst, icat/entity.py
Add an optional keyword argument `keepInstRel` to `Entity.truncateRelations()`. If set to `True`, only the one to many relationships will be deleted, but the many to one relationships will be kept. If `False`, the default, all relationships will be deleted.
=> Add an optional keyword argument keepInstRel to Entity.truncateRelations()

CHANGES.rst, doc/src/client.rst, icat/client.py, tests/test_04_client_cleanup.py
Use a `weakref.WeakValueDictionary` in `client.Register` to avoid spurious references to `Client` objects preventing these objects to be discarded by the garbage collector.
Close #111.
=> Fix a memory leak in Client.Register

CHANGES.rst, icat/dump_queries.py
If talking to an ICAT server older than 5.0 that does not have `DataPublication`, return an empty list from `getDataPublicationQueries()` rather than raising `EntityTypeError`.
Strictly speaking, the previous behavior was not a bug, as it was as intended and documented. But in the meanwhile, I started to question these intentions.
=> Return an empty list from getDataPublicationQueries() for old ICAT servers

CHANGES.rst, doc/src/client.rst, doc/src/config.rst, doc/src/dump_queries.rst, doc/src/entities.rst, doc/src/tutorial-config-advanced.rst, doc/src/tutorial-config.rst, doc/src/tutorial-create.rst, doc/src/tutorial-edit.rst, doc/src/tutorial-hello.rst, doc/src/tutorial-ids.rst, doc/src/tutorial-search.rst, doc/src/tutorial.rst, icat/client.py, icat/config.py, icat/dump_queries.py, icat/dumpfile.py, icat/entities.py, icat/entity.py, icat/exception.py, icat/helper.py
Review the documentation and update some outdated parts:
Close #126.
=> Review documentation

CHANGES.rst, doc/examples/create-datafile.py, icat/dumpfile_xml.py, icat/dumpfile_yaml.py, setup.py
Tested with Python 3.12.0b1, so let's assume it will work with the Python 3.12 release as well and update the package metadata accordingly.
Fixed deprecation warnings: `datetime.datetime.utcfromtimestamp()` and `datetime.datetime.utcnow()` are deprecated in Python 3.12, so avoid using them. At the same time, take the opportunity to simplify some code by depending on `datetime.timezone.utc`: it is in the standard library since Python 3.2, so no need any more to check its availability.
**Note**:  Python 3.12.0b1 breaks the current release version of [lxml](https://lxml.de/).  This is expected to be fixed in lxml 5.0.0 but that version has not been released yet. So the tests were not complete, I could not run any of the tests that depend on lxml with Python 3.12.0b1. We might wait a while …
=> Adapt to upcoming Python 3.12

CHANGES.rst, doc/examples/icatdump-4.10.xml, doc/examples/icatdump-4.10.yaml, doc/examples/icatdump-4.4.xml, doc/examples/icatdump-4.4.yaml, doc/examples/icatdump-4.7.xml, doc/examples/icatdump-4.7.yaml, doc/examples/icatdump-5.0.xml, doc/examples/icatdump-5.0.yaml, doc/examples/ingest-sample-ds.xml, doc/examples/init-icat.py, doc/icatdata-4.10.xsd, doc/icatdata-4.3.xsd, doc/icatdata-4.4.xsd, doc/icatdata-4.7.xsd, doc/icatdata-5.0.xsd, icat/dumpfile_xml.py, setup.py, tests/data/legacy-icatdump-4.10.xml, tests/data/legacy-icatdump-4.10.yaml, tests/data/legacy-icatdump-4.4.xml, tests/data/legacy-icatdump-4.4.yaml, tests/data/legacy-icatdump-4.7.xml, tests/data/legacy-icatdump-4.7.yaml, tests/data/ref-icatdump-5.0.xml, tests/data/ref-icatdump-5.0.yaml, tests/data/summary-4, tests/data/summary-5, tests/test_06_icatingest.py, tests/test_06_query.py
Enhance the XML ICAT data file format that is read by the `icat.dumpfile_xml` to allow the use reference keys for related objects when referencing an object by attributes.
Close #122. (See that issue on what this is all about.)
=> Implemented referencing related objects by reference key in XML ICAT data file format

.rtd-require
Fix the documentation build at Read the Docs.
RTD was failing. Apparently this was because the RTD defaults made a version jump from Sphinx version 1.8.6 to 7.2.6, which included a version bump for Jinja2 from 3.0.3 to 3.1.2. In our RTD requirements file, we made an upgrade of Sphinx to version 2, which now, with the new defaults, means a downgrade. It seems that Jinja2 3.1.2 is incompatible with Sphinx 2.
For the time being, we fix that by downgrading Jinja2 to < 3.1. In the long run, we should consider upgrading Sphinx instead. But I'd like to do more testing before doing that.
=> Fix Read the Docs build

CHANGES.rst, icat/ids.py, tests/test_03_getversion.py
Review `IDSClient.getApiVersion()` and `IDSClient.version()` and make sure they will yield correct results also for `ids.server` 2.0 and newer. Fix #131.
=> Fix IDSClient.getApiVersion()

CHANGES.rst, icat/client.py
In the constructor of class Client, set all object attributes to some value before doing anything that may fail, even to some bogus value that may need to be overwritten later on, in order to guarantee that at least the attribute is set.
Fix #132.
=> Fix spurious AttributeError on cleanup

CHANGES.rst, doc/examples/metadata-5.0-sep.xml, doc/src/ingest.rst, etc/ingest-10.xsd, etc/ingest.xslt, setup.py, tests/test_06_ingest.py
Fix `ingest-10.xsd` and `ingest.xslt` used by module `icat.ingest` so that the result of the transformation is valid according to the schema for ICAT data files.
Note that this constitutes an incompatible change regarding the input that `icat.ingest` accepts: the order of `datasetTechnique` and `datasetInstrument` subelements of `data` need to be changed.
Close #138.
=> Fix XSD and XSLT files used in icat.ingest to produce valid ICAT data files

CHANGES.rst, doc/examples/metadata-sample.xml, doc/src/ingest.rst, etc/ingest-10.xsd, etc/ingest-11.xsd, etc/ingest.xslt, icat/ingest.py, setup.py, tests/test_06_ingest.py
Add version 1.1 of the ingest file format that features references to a `Sample` from a `Dataset`. Close #125.
=> Add support to link datasets with samples in icat.ingest

CHANGES.rst, MANIFEST.in, doc/src/ingest.rst, icat/ingest.py, tests/data/metadata-custom-icatingest.xml, tests/data/metadata-custom-myingest.xml, tests/data/myingest.xsd, tests/data/myingest.xslt, tests/test_06_ingest.py
As pointed out in #143, the current way of controlling the XSLT file to use for processing the input in class `icat.ingest.IngestReader` is inconvenient to customize the behavior in some cases.
This PR now drops the class attribute `XSLT_name` in favour of `XSLT_Map`. This new class attribute maps the name of the root element in the input to the file name of the XSLT file to use to process that data. This way, customized classes may add their own input format while still keeping the standard format providing by python-icat as an alternative. This is not only more convenient, but also more consistent with the way the name of XSD file is controlled.
Close #143.
=> icat.ingest.IngestReader: drop class attribute XSLT_name in favour of a new XSLT_Map

CHANGES.rst, src/icat/ingest.py, tests/test_06_ingest.py
Call `XMLSchema().assertValid()` rather than `XMLSchema().validate()` which raises a more meaningful error message.  Pass that error message in the `InvalidIngestFileError` raised by `IngestReader`. As a result a much more meaningful error message is provided than a plain "Invalid ingest file: validation failed".
=> Provide a meaningful error message if the IngestReader  input fails XSD validation

CHANGES.rst, src/icat/client.py
Fix a logical error in a code example in the docstring of `Client.searchChunked()`.
=> Fix a documentation error

CHANGES.rst, tests/test_07_entity_validate.py
In the test module `test_07_entity_validate` is a name collision with two different tests having the same name.  Fix that.
=> Fix duplicate test name test_07_entity_validate

CHANGES.rst, src/icat/config.py, tests/test_01_config.py
Add an option to completely disable parsing of command line arguments in class `Config`: if the special value `False` is passed in the (already exiting) keyword argument to the constructor.  Close #155.
=> Implement disabling of command line arguments in config

CHANGES.rst, doc/src/ingest.rst, src/icat/ingest.py
Remove note on experimental status from `icat.ingest` module documentation.
=> icat.ingest now considered stable

CHANGES.rst, doc/src/ingest.rst, etc/ingest.xslt, src/icat/ingest.py, tests/test_06_ingest.py
Add class attributes `Dataset_complete` and `DatasetType_name` to `IngestReader` to make the values of `complete` attributes of datasets and the name of the `type` they are related to respectively configurable. These values are (and should be) prescribed in the process of reading metadata from XML ingest files into ICAT, but they were hard coded in the provided XSLT file. Close #160.
=> Add class attributes to IngestReader to configure prescribed values

CHANGES.rst, src/icat/ingest.py, tests/data/ingest-env.xslt, tests/test_06_ingest.py
I merged #161 a little bit prematurely, a few more things should have been included:
- add tests to verify that the values of the new class attributes `Dataset_complete` and `DatasetType_name` are indeed properly set in the ingested data,
- add some more documentation on that new feature, including some caveats,
- while we are at it, extend the existing test for the `_environment` element to also add a custom attribute.
=> More tests and documentation on class attributes in IngestReader to configure prescribed values

CHANGES.rst, doc/examples/dumpinvestigation.py, doc/examples/ingest.py
The `dumpinvestigation.py` example script was broken: it included the same objects multiple times in the output in some case.  Thoroughly review it.  Also fix a typo in a doc string the `ingest.py` example script.
=> Fix dumpinvestigation.py example script

doc/src/ingest.rst
Fix the documentation: #161 added two more attributes to the environment element ingested by `IngestReader` into the metadata, but failed to mention these new attributes in the [documentation](https://python-icat.readthedocs.io/en/1.5.0/ingest.html#the-environment-element).
=> Add missing documentation on the environment ingested by IngestReader into the input

CHANGES.rst, doc/src/client.rst, src/icat/client.py, tests/conftest.py, tests/test_06_ids.py
Add a IDS custom method `restoreData()` to class `Client`.  This method checks the status of the data in IDS, requests a restore if the data is not already online and waits for the restore to complete.
I found three independent implementations of that in my own code, so apparently this is needed as a helper in the library.
Draft status: should still add a test.
=> Add method Client.restoreData()
